workflows:
  ios-workflow:
    name: Assurance
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Set iOS deployment target
        script: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' assurance/ios/Runner.xcodeproj/project.pbxproj
      - name: Pod install
        script: |
          cd assurance/ios && pod install && cd ../..
      - name: Build IPA
        script: |
          cd assurance && flutter build ipa --release --no-codesign
    artifacts:
      - assurance/build/ios/ipa/*.ipa
      - assurance/build/ios/archive/*.xcarchive