workflows:
  ios-workflow:
    name: Assurance Wireless iOS
    instance_type: mac_mini_m2
    environment:
      flutter: stable

    scripts:
      - name: Build IPA
        script: |
          flutter pub get
          cd ios && pod install && cd ..
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - "**/*.ipa"
      - "**/*.app"

    publishing:
      email:
        recipients:
          - enwar.d@outlook.com
        notify:
          success: true
          failure: true