name: assurance
description: Unofficial Assurance Wireless MyAccount app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  webview_flutter_wkwebview: ^3.26.0

flutter:
  uses-material-design: true